### ISSUE TITLE
XoFTR is very interesting,and maybe  you  can share the code with me. I will apply this tech on my work . Thank you very much!

### ISSUE THREAD

**Issue by hanlilican** [OnderT/XoFTR#1]
XoFTR is very interesting,and maybe  you  can share the code with me. I will apply this tech on my work . Thank you very much!

**Comment by OnderT** [comment]
We sincerely appreciate your interest in our work. After final revisions and organization, we aim to release the refined code and dataset in a couple of months.

Best
